pages:
  label: learnkit.lms::lang.fields.pages
  view:
    toolbarButtons: create|delete|link|unlink
    list: $/learnkit/lms/models/page/columns_sort.yaml
    recordUrl: learnkit/lms/pages/update/:id
    defaultSort:
      column: sort_order
      direction: asc
  manage:
    form: $/learnkit/lms/models/page/fields_no_relation.yaml
users:
  label: learnkit.lms::lang.fields.users
  view:
    toolbarButtons: link|unlink
    list: $/rainlab/user/models/user/columns.yaml
    recordUrl: rainlab/user/users/update/:id
    defaultSort:
      column: surname
      direction: asc
  manage:
    form: $/rainlab/user/models/user/fields.yaml