fields:
  data_type:
    label: Chart type
    span: left
    type: dropdown
    options:
      subjectResults: Subject results
    trigger:
      action: show
      field: content_block_type
      condition: value[learnkit.lms::chart]
  sections:
    label: Sections
    type: repeater
    span: right
    trigger:
      action: show
      field: content_block_type
      condition: value[learnkit.lms::chart]
    form:
      fields:
        section_key:
          label: Section key
          type: text
          span: left
        section_label:
          label: Section label
          type: text
          span: right
  show_y:
    label: Show Y
    span: left
    type: switch
    default: true
    trigger:
      action: show
      field: content_block_type
      condition: value[learnkit.lms::chart]
  show_x:
    label: Show X
    span: left
    type: switch
    default: true
    trigger:
      action: show
      field: content_block_type
      condition: value[learnkit.lms::chart]
  colors:
    label: Colors
    span: left
    type: repeater
    trigger:
      action: show
      field: content_block_type
      condition: value[learnkit.lms::chart]
    form:
      fields:
        color:
          label: Color
          span: full
          type: colorpicker